### ISSUE TITLE
As a stack git dependency, symbolic link dest not found.

### ISSUE THREAD

**Issue by philderbeast** [monadfix/shower#23]
This repo doesn't play nice with stack on mac when pulled in as a git dependency.

```
> stack new --bare use-shower
```

```yaml
resolver: lts-18.28
packages:
- .
extra-deps:
- git: https://github.com/monadfix/shower.git
  commit: 3e02d92e0500e41b4e9932294f4960463a7222d4
```

```
> stack build
Cloning 3e02d92e0500e41b4e9932294f4960463a7222d4 from https://github.com/monadfix/shower.git
Unsupported tarball from
/private/var/folders/31/zb67fgcs66q4n3cs_wn134zr0000gn/T/with-repo-archive48693/foo.tar:
 Symbolic link dest not found from ./js/reflex-platform/README.lhs to README.md,
 looking for js/reflex-platform/README.md.
This may indicate that the source is a git archive which uses git-annex.
See https://github.com/commercialhaskell/stack/issues/4579 for further information.
```

```
> stack --version
Version 2.9.1, Git revision 409d56031b4240221d656db09b2ba476fe6bb5b1 x86_64 hpack-0.35.0
> sw_vers
ProductName:	macOS
ProductVersion:	11.6.8
BuildVersion:	20G730
```

This is not a problem on ubuntu linux.
